# Generated by Django 5.1.7 on 2025-03-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reservation',
            field=models.ManyToManyField(to='main_app.reservation'),
        ),
    ]
