# Generated by Django 5.1.7 on 2025-03-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_book_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='book',
            field=models.ManyToManyField(to='main_app.book'),
        ),
    ]
